spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    producer:
      acks: -1
      retries: 5
      properties:
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
        security.protocol: PLAINTEXT
        sasl.mechanism: PLAIN
        transactional.id: "s3-source-connector"

    consumer:
      max-poll-records: 50_000 # default: 1000
      properties:
        poll.ms: 100 # default: 100
        fetch.max.bytes: 57671680  # default: 57671680 (55MB)
        max.partition.fetch.bytes: 57671680 # default: 1MB
        # static membership
        #        group.instance.id: stateless-group
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: org.apache.kafka.common.serialization.LongDeserializer
        security.protocol: PLAINTEXT
        sasl.mechanism: PLAIN
    admin:
      security:
        protocol: PLAINTEXT


management:
  # /actuator/prometheus 노출
  endpoints:
    prometheus:
      enabled: true
    # By default, only the health endpoint is exposed over HTTP and JMX
    health:
      enabled: true
    # Actuator 페이지로 노출할 endpoint 에 prometheus 포함
    web:
      exposure:
        include: "prometheus,health,info,metrics"
